on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

 build:

  runs-on: ubuntu-latest

  call-basic-validation:
    name: Basic validation
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main

  steps:
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test:ci  