name: Install dependencies
  run: |
      if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
          npm ci
        else
          npm i
      fi

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-basic-validation:
    name: Basic validation
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main