name: Run JavaScript examples

on:
  workflow_dispatch:
  schedule:
    - cron: '40 22 * * *'
  pull_request:
    branches:
      - master
    paths:
      - 'vuejs-gitfinder/src/**'
  push:
    branches:
      - master
    paths:
      - 'vuejs-gitfinder/src/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  # ~~~~~~~~~~~~~~~~~~ Cypress v9 and below (using Legacy configuration) ~~~~~~~~~~~~~~~~~~~ #
 my_first_job:
    name: My first job
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Install Firefox
      uses: abhi1693/setup-browser@v0.3.5
      with:
        browser: firefox
        version: latest
    - name: Delete all
      working-directory: 
      run: rm -Rf node_modules 
    - name: Install requirements
      working-directory: 
      run:  npm install
    - name: User local
      working-directory: 
      run: sudo chown -R $USER /usr/local
    - name: Mode local
      working-directory: 
      run: chmod -R a+x node_modules
     - name: Running Watch
      working-directory: 
      run:  npm run watch
    - name: Run tests
      uses: nick-invision/retry@v2.8.3
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: npm test
