name: Run JavaScript examples

on:
  workflow_dispatch:
  schedule:
    - cron: '40 22 * * *'
  pull_request:
    branches:
      - test_inputs
    paths:
      - 'vuejs-gitfinder/src/**'
  push:
    branches:
      - test_inputs
    paths:
      - 'vuejs-gitfinder/src/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Edge
      uses: browser-actions/setup-edge@latest
    - name: Install Firefox
      uses: abhi1693/setup-browser@v0.3.5
      with:
        browser: firefox
        version: latest
    - name: Delete all
      working-directory: 
      run: |
        rm -Rf node_modules 
        npm install --legacy-peer-deps
        sudo chown -R $USER /usr/local
        chmod -R a+x node_modules
        npm run watch
        npm test
   