name: Node.js CI

on:
  push:
    branches: [ test_inputs ]
  pull_request:
    branches: [ test_inputs ]

jobs:
  build:
  test_example:
    
    runs-on: ubuntu-latest
  
    strategy:
     
     fail-fast: false
     matrix:
      os: [ ubuntu-latest, windows-latest, macos-latest ]
      
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Start Xvfb
        if: matrix.os == 'ubuntu-latest'
        run: Xvfb :99 &
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install Edge
        uses: browser-actions/setup-edge@latest
      - name: Action Checkout
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm package-lock.json 
      - run: rm -rf node_modules
      - run: npm install     
      - run: npm ci --no-save --legacy-peer-deps
      - run: npm run build --if-present
      - run: npm test --http-parser=legacy