name: Node.js CI

on:
  push:
    branches: [ test_inputs ]
  pull_request:
    branches: [ test_inputs ]

jobs:
  build:
  test_example:
    
    runs-on: ubuntu-latest
  
    strategy:
     matrix:
      node-version: [15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm package-lock.json 
      - run: rm -rf node_modules
      - run: npm install     
      - run: npm ci --no-save --legacy-peer-deps
      - run: npm run build --if-present
      - run: npm test --http-parser=legacy