name: Main

on:
  pull_request:
   path-ignore:
    - '**.md'
  push:
   branches:
    - test_inputs
    - releases/*
   paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 5, 6, 7 ]
    name: Node ${{ matrix.node }} sample
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      # caching NPM dependencies
      # https://github.com/actions/cache/blob/master/examples.md#node---npm
       with:
        node-version: ${{ matrix.node }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run reinstall --legacy-peer-deps
      - run: npm test

