name: Node.js CI

on:
  push:
    branches: [ test_inputs ]
  pull_request:
    branches: [ test_inputs ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm package-lock.json 
      - run: rm -rf node_modules
      - run: npm install     
      - run: npm ci --no-save --legacy-peer-deps
      - run: npm run build --if-present
      - run: npx nightwatch --env chrome
      - run: npm run test --env chrome
      - run: npx nightwatch --env default
      - run: npm run test --env default
      - run: npm test --http-parser=legacy
      